# Generated by Django 4.1.3 on 2023-05-09 17:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20230503_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkings',
            old_name='Street',
            new_name='street',
        ),
        migrations.RemoveField(
            model_name='parkings',
            name='remaning_slot',
        ),
        migrations.AddField(
            model_name='parkings',
            name='remaining_slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='intime',
            field=models.TimeField(default=datetime.time(17, 33, 9, 851710), null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pdate',
            field=models.DateField(default=datetime.date(2023, 5, 9), null=True),
        ),
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.parkings')),
            ],
        ),
    ]
