# Generated by Django 4.1.3 on 2023-05-10 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_alter_vehicle_intime_alter_vehicle_pdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='intime',
            field=models.TimeField(default=datetime.time(9, 47, 48, 156916), null=True),
        ),
    ]
