# Generated by Django 4.1.3 on 2023-05-10 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_alter_vehicle_intime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='intime',
            field=models.TimeField(default=datetime.time(9, 51, 47, 600993), null=True),
        ),
    ]
