# Generated by Django 4.1.3 on 2023-05-10 10:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_alter_vehicle_intime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='intime',
            field=models.TimeField(default=datetime.time(10, 37, 12, 712188), null=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.slots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.user_login')),
            ],
        ),
    ]
