# Generated by Django 4.1.3 on 2023-05-10 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_alter_vehicle_intime_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='intiime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='outtime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='intime',
            field=models.TimeField(default=datetime.time(10, 42, 10, 270683), null=True),
        ),
    ]
