# Generated by Django 4.1.3 on 2023-05-25 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_booking_intiime_booking_outtime_alter_vehicle_intime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='intiime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='intime',
            field=models.TimeField(default=datetime.time(12, 9, 58, 212673), null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pdate',
            field=models.DateField(default=datetime.date(2023, 5, 25), null=True),
        ),
    ]
