# Generated by Django 3.2.19 on 2023-05-27 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0012_booking_vehicle_alter_vehicle_intime'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='parkingcharge',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='intime',
            field=models.TimeField(default=datetime.time(16, 13, 29, 377351), null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pdate',
            field=models.DateField(default=datetime.date(2023, 5, 27), null=True),
        ),
    ]
