# Generated by Django 3.2.19 on 2023-05-27 18:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0014_auto_20230527_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='outtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='intime',
            field=models.TimeField(default=datetime.time(18, 25, 24, 608135), null=True),
        ),
    ]
